### ISSUE TITLE
Find devise user not working

### ISSUE THREAD

**Issue by jawosis** [shenoudab/devise_couch#4]
I set up devise and devise_couch and could successfully create a user vía devise.
But once I want to sign in or send reset password instructions the user can not be found.

A look to the CouchDB log shows that there is just a PUT request to re-create the User's database  - do I have to explicitly create devise views for the Devise (in my case User) model?

**Comment by shenoudab** [comment]
Dear, 

   just be sure that you are using devise_couch from master and also devise_couch --pre

 also cerate views for devise authentication_keys as pacified  in config/initializers/devsie.rb 
like if you have authentication_keys = [:email] add to your model view_by :email

**Comment by cgarvis** [comment]
I'm having the same issue. I have the following

Gemfile:
gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'couchrest_model', :git => 'git://github.com/couchrest/couchrest_model.git'
gem 'devise'
gem 'devise_couch'

models/user.rb:
class User < CouchRest::Model::Base
  use_database CouchServer.default_database

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  view_by :email

end

**Comment by shenoudab** [comment]
you can update you gems as follow :

gem 'orm_adapter', :git => 'git://github.com/shenoudab/orm_adapter.git'
gem 'devise', '1.2.rc'
gem 'devise_couch', :git => 'git://github.com/shenoudab/devise_couch.git'

and also set the devise.rb initializer as specified in the previous comment.

**Comment by baphled** [comment]
I seem to have the same issue as above, I've setup my gems as you have suggested and have a view for the username which is what I'm authenticating against.

**Comment by cgarvis** [comment]
I set the devise.rb initializer like you said and still had issues.  I haven't tried your orm_adapter but I did find thatSam Lown's fork worked.  See it at https://github.com/samlown/devise_couchrest_model

**Comment by shenoudab** [comment]
Happy new year, 

 please, provide me with the issues raised so i can check that case for you.

**Comment by baphled** [comment]
Happy new year to you too. I've upgraded my version of devise_couch and devise to the latest versions. Now I am unable to sign in with any user. Even when I create a new account the user is created I am redirected to the sign in page and am unable to log in.

It appears that the user model sign_in count is increasing suggesting to me that the user is found, so it may not be a devise_couch issue but having said that I can not find other people having similar issues using other ORMs.

**Comment by shenoudab** [comment]
try using devise version '1.2.rc' as it works for me.
and update your Gemfile as Follow :

gem 'devise', '1.2.rc'
gem 'couchrest', :git => 'git://github.com/couchrest/couchrest.git'
gem 'couchrest_model', :git => 'git://github.com/couchrest/couchrest_model.git'

**Comment by baphled** [comment]
My gem file already has the above gems setup. I still get the same issue of not being able to successfully login.

gem 'devise', '1.2.rc'
gem 'couchrest', :git => "http://github.com/couchrest/couchrest.git"
gem 'couchrest_model', :git => 'git://github.com/couchrest/couchrest_model.git'
gem 'devise_couch', :git => 'git://github.com/shenoudab/devise_couch.git'
gem 'orm_adapter', :git => 'git://github.com/shenoudab/orm_adapter.git'

**Comment by SynnaxCrab** [comment]
My Gems:

gem 'orm_adapter', :git => 'git://github.com/shenoudab/orm_adapter.git'
gem 'devise', '1.2.rc'
gem 'devise_couch', :git => 'git://github.com/shenoudab/devise_couch.git'
gem 'couchrest_model', :git => 'git://github.com/couchrest/couchrest_model.git'

User.rb:
view_by :email

it works. 
but when sign_in, there was a "'PUT' /devise_couch 412" in CouchDB console. is this related?

**Comment by shenoudab** [comment]
please, provide me with more details from this CouchDB console.

**Comment by baphled** [comment]
@winfield, yup that looks like the same error I am currently having.

@shenoudab Here's a copy of the related log

<pre><code>

[Mon, 03 Jan 2011 16:32:55 GMT] [info] [<0.25269.1>] 127.0.0.1 - - 'GET' /cvme_development/3042aa9cc85b117bca65cf0336976f16 200

[Mon, 03 Jan 2011 16:32:56 GMT] [info] [<0.25306.1>] 127.0.0.1 - - 'GET' /cvme_development/_design/User 200

[Mon, 03 Jan 2011 16:32:56 GMT] [info] [<0.1025.0>] checkpointing view update at seq 1075 for cvme_development _design/User

[Mon, 03 Jan 2011 16:32:56 GMT] [info] [<0.25308.1>] 127.0.0.1 - - 'GET' /cvme_development/_design/User/_view/by_admin?include_docs=true 200

[Mon, 03 Jan 2011 16:34:11 GMT] [info] [<0.25309.1>] 127.0.0.1 - - 'PUT' /cvme_development 412

[Mon, 03 Jan 2011 16:34:42 GMT] [info] [<0.25391.1>] 127.0.0.1 - - 'GET' /cvme_development/_design/User 200

[Mon, 03 Jan 2011 16:34:42 GMT] [info] [<0.25424.1>] 127.0.0.1 - - 'GET' /cvme_development/_design/User/_view/by_username?key=%22baphled%22&limit=1&include_docs=true 200

</code></pre>

**Comment by shenoudab** [comment]
i have publish a rails application example for devise using couchdb using my lib devise_couch. github.com/shenoudab/devise_couch_example

i create alot of examples with different email and they are working fine.

**Comment by baphled** [comment]
Thanks for taking the time to put a demo up.

I've had a little play with your example and its seems to work using the default settings.

I've reverted my version so that I have the same settings as you do but I still come up with the same problem.

I think the issue is with the actual find in the schema. When there is not much data in couch everything seems fine but I'm working with pre-existing data which is being picked up during the find call.

<pre><code>
[info] [<0.2005.0>] 192.168.0.2 - - 'GET' /cvme_development/_design/User/_view/by_username?key=%22baphled%22&limit=1&include_docs=true 200
[info] [<0.2006.0>] 192.168.0.2 - - 'GET' /cvme_development/_design/User/_view/by_admin?include_docs=true 200
[info] [<0.2007.0>] 192.168.0.2 - - 'PUT' /cvme_development/3042aa9cc85b117bca65cf0336976f16 201
[info] [<0.2008.0>] 192.168.0.2 - - 'GET' /cvme_development/_design/User 200
[info] [<0.1033.0>] checkpointing view update at seq 431 for cvme_development _design/User
[info] [<0.2010.0>] 192.168.0.2 - - 'GET' /cvme_development/_design/User/_view/all?conditions=%7B%3Aid%3D%3E%223042aa9cc85b117bca65cf0336976f16%22%7D&limit=1&include_docs=true 200
</code></pre>


I decided to try this manually and copied the last query above and got the results below.

<pre><code>
 curl http://192.168.0.4:5984/cvme_development/_design/User/_view/all?conditions=%7B%3Aid%3D%3E%223042aa9cc85b117bca65cf0336976f16%22%7D&limit=1&include_docs=true 
{"total_rows":16,"offset":0,"rows":[
{"id":"11bc711c1f8e665c40c8ce07355ba43f","key":"11bc711c1f8e665c40c8ce07355ba43f","value":1},
{"id":"3042aa9cc85b117bca65cf0336976f16","key":"3042aa9cc85b117bca65cf0336976f16","value":1},
{"id":"4f0d263b622843f01d27ce093a1e341b","key":"4f0d263b622843f01d27ce093a1e341b","value":1},
{"id":"73a0ff0c8ebde7aa933e8ea4b83e83f2","key":"73a0ff0c8ebde7aa933e8ea4b83e83f2","value":1},
{"id":"84e8feba6d2483661f1fd0274c3e963c","key":"84e8feba6d2483661f1fd0274c3e963c","value":1},
{"id":"b39e43b75a0abad822c8d6310f5fe18c","key":"b39e43b75a0abad822c8d6310f5fe18c","value":1},
{"id":"b5080baf82d3662dfc6163b17a3ecf9c","key":"b5080baf82d3662dfc6163b17a3ecf9c","value":1},
{"id":"b5080baf82d3662dfc6163b17a3ee031","key":"b5080baf82d3662dfc6163b17a3ee031","value":1},
{"id":"b5080baf82d3662dfc6163b17a5ef5a3","key":"b5080baf82d3662dfc6163b17a5ef5a3","value":1},
{"id":"b5080baf82d3662dfc6163b17a7e390d","key":"b5080baf82d3662dfc6163b17a7e390d","value":1},
{"id":"b5080baf82d3662dfc6163b17a9d5ee4","key":"b5080baf82d3662dfc6163b17a9d5ee4","value":1},
{"id":"b5080baf82d3662dfc6163b17abd467b","key":"b5080baf82d3662dfc6163b17abd467b","value":1},
{"id":"b5080baf82d3662dfc6163b17adbbafa","key":"b5080baf82d3662dfc6163b17adbbafa","value":1},
{"id":"b5080baf82d3662dfc6163b17afac09f","key":"b5080baf82d3662dfc6163b17afac09f","value":1},
{"id":"c4db78f1733a84da2551a7e61d5150a8","key":"c4db78f1733a84da2551a7e61d5150a8","value":1},
{"id":"f7cb9d445386fc09baf10887bd1a26ec","key":"f7cb9d445386fc09baf10887bd1a26ec","value":1}
]}
</code></pre>


I have yet to test my setup with an empty couch instance but seeing as there should be a limit on the amount of results brought back it feels like something is being overlooked.

**Comment by shenoudab** [comment]
kindly,  update to the new published  updates for orm_adaptor and devise_couch_example. which will going to solve the reported problems ... please, check and feed me back.

**Comment by shannonwells** [comment]
I was seeing the same issue.  I traced the problem, for me at least, devise was not using the override of find_for_authentication in devise_couch; instead it was calling its own method, which goes to get() in couchrest_model directly (couchrest/model/document_queries.rb:68).  It passes id = :first, which of course will fail.  That is why it always returns :invalid response.  Apologies to those who already knew this, just thought I would add the explanation I found.

I had been using devise 1.1.5 and did not have orm_adapter.  I was not using the github versions of couchrest and couchrest_model.   So doing the update to all 6 things that shenoudab recommended did enable login to work:

gem 'devise', '1.2.rc'
gem 'orm_adapter', :git => 'git://github.com/shenoudab/orm_adapter.git'
gem 'devise_couch', :git => 'git://github.com/shenoudab/devise_couch.git'

gem 'couchrest', :git => 'git://github.com/couchrest/couchrest.git'
gem 'couchrest_model', :git => 'git://github.com/couchrest/couchrest_model.git'
gem 'rails3-generators', :git => 'git://github.com/shenoudab/rails3-generators.git'

**Comment by baphled** [comment]
I actually managed to resolve this issue a couple of months ago. It turned out the issue was with orm_adapter which I've resolved and have had no problems since.
